USE taller_mecanico;

ALTER TABLE servicios
ADD COLUMN IF NOT EXISTS fecha_ingreso DATETIME DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS fecha_entrega DATETIME NULL,
ADD COLUMN IF NOT EXISTS kilometraje INT NULL,
ADD COLUMN IF NOT EXISTS descripcion TEXT NULL,
ADD COLUMN IF NOT EXISTS estado VARCHAR(30) DEFAULT 'RECIBIDO',
ADD COLUMN IF NOT EXISTS total DECIMAL(10,2) DEFAULT 0.00;

ALTER TABLE detalletrabajo
MODIFY id_repuesto INT NULL,
ADD COLUMN IF NOT EXISTS descripcion_trabajo VARCHAR(200) NULL,
ADD COLUMN IF NOT EXISTS costo_mano_obra DECIMAL(10,2) DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS fecha DATETIME DEFAULT CURRENT_TIMESTAMP;

